### ISSUE TITLE
feat: add functionality to support publishing pre-release to a release

### ISSUE THREAD

**Issue by xunholy** [eregon/publish-release#5]
Just been attempting to publish a pre-release into a release as we're using release tracks and promoting them with our repo.

Firstly, this tool has been awesome, would you consider adding the functionality to support promoting a pre-release to become a release? We're using something like follows:

```yaml
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Release
        uses: InsonusK/get-latest-release@v1.0.1
        id: release_id
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|release"
          view_top: 5

      - name: "Print Release Info"
        run: |
          echo "id: ${{ steps.release_id.outputs.id }}"
          echo "name: ${{ steps.release_id.outputs.name }}"
          echo "tag_name: ${{ steps.release_id.outputs.tag_name }}"
          echo "created_at: ${{ steps.release_id.outputs.created_atd }}"
          echo "draft: ${{ steps.release_id.outputs.draft }}"
          echo "prerelease: ${{ steps.release_id.outputs.prerelease }}"

      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PLATFORM_SECRET_MGMT_ACTION_TOKEN }}
        with:
          release_id: ${{ steps.release_id.outputs.id }}
```
